### PR TITLE
New Update-AssemblyVersion cmdlet.

### PR DESCRIPTION
**Pull request by ChrisLambrou**
Cmdlet that uses regular expression magic to update the AssemblyVersion, AssemblyFileVersion and AssemblyInformationalVersion attributes in a source file, typically AssemblyInfo.cs.

### CODE REVIEW

**Comment by nyctef** [comment]
Minor complaint: looks like this'll write out with utf8+BOM encoding by default, which is [kind of icky](http://utf8everywhere.org/#faq.boms). I don't know if we have (or should have) any general rules on file encoding, though.

**Comment by nyctef** [comment]
Removing the two 

```
        Author: Chris Lambrou
        Copyright 2016, Red Gate Software Limited
```
lines makes `Get-Help Update-AssemblyVersion` work and the tests pass - do we need those? (maybe it could go into `.DESCRIPTION` or `.NOTES`)

**Comment by ChrisLambrou** [comment]
I just copied them from another file. Should get rid of them everywhere if they break Get-Help.

**Comment by ChrisLambrou** [comment]
Regarding the bom, we could make a special case for utf8 and use File.WriteAllText with and appropriately crafted Encoding instance. Maybe another private helper cmdlet as an alternative to Out-File?

**Comment by nicolasvan** [comment]
For the BOM thing, I would keep using powershell `-Encoding UTF8` and trust powershell to do the right thing. BOM or not BOM, as long as this doesn't break our builds we are probably fine....

Maybe one day Microsoft will remove the BOM ?

@nyctef the link you give also says we should use `\n` even on windows, which we probably won't follow either :stuck_out_tongue:

**Comment by ChrisLambrou** [comment]
What link?

**Comment by nicolasvan** [comment]
http://utf8everywhere.org/#faq.boms 
http://utf8everywhere.org/#faq.crlf

**Comment by nyctef** [comment]
> @nyctef the link you give also says we should use `\n` even on windows, which we probably won't follow either :stuck_out_tongue: 

windows newlines (ie CRLF) are also dumb and terrible, but that's another holy war for another time :stuck_out_tongue:

**Comment by ChrisLambrou** [comment]
Meh to boms and line endings. I've gone through and tidied up all the help docs a bit (not just my new cmdlet).

**Comment by ChrisLambrou** [comment]
Ah, that link! Sorry, was up late following the SF saga and am a bit bleary eyed this morning. :|

**Comment by ChrisLambrou** [comment]
Okay, the documentation tests now pass. Turns out that the `Get-Help` cmdlet is truly rubbish. It basically insists that the special code comments are the first thing in the file, so it was failing on the two cmdlet that had `#requires -Version X` directives automatically inserted at the top of the file by PowerShell ISE.

Anyway, still not ready to merge. Although I tried it out last night on another project and it basically appears to work okay, I haven't written any tests for this, yet, which I intend to do tomorrow sometime.

**Comment by nyctef** [comment]
It's only doing what the docs say it does :stuck_out_tongue: 

https://technet.microsoft.com/en-us/library/hh847834.aspx
> Comment-based help for a script can appear in one of the following two
    locations in the script.
>    -- At the beginning of the script file. Script help can be preceded in the
       script only by comments and blank lines.
>    -- [...]

**Comment by ChrisLambrou** [comment]
That `#requires -Version` directive *is* a comment! I stand by my criticism of `Get-Help`. I found dozens of other bugs in it when I wrote the `XmlDoc2CmdletDoc` tool, too.

**Comment by nyctef** [comment]
Nah, it's just [a statement that sneakily looks like a comment](https://technet.microsoft.com/en-us/library/hh847765.aspx) :wink:

**Comment by ChrisLambrou** [comment]
I've added some tests and corresponding bug fixes. :shipit:?

**Comment by nicolasvan** [comment]
:+1:

**Pull request merged**
